myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'
urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'about', views.about, name='about'),
    path(r'findcourses', views.findcourses, name='find_courses'),
    path(r'place_order', views.place_order, name='place_order'),
    path(r'review', views.review, name='review'),
    path(r'login', views.user_login, name='login'),
    path(r'logout', views.user_logout, name='logout'),
    path(r'register', views.register, name='register'),
    path(r'edit_profile', views.edit_profile, name='edit_profile'),
    path(r'change_password', views.change_password, name='change_password'),
    path(r'myaccount', views.myaccount, name='myaccount'),
    path(r'course/<course_id>', views.course, name='course'),
    path(r'forget_password', views.forget_password, name='forget_password'),
    path(r'<topic_id>', views.details, name='details'),
]

mysiteS21/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.core.validators import MinValueValidator, MaxValueValidator, MaxLengthValidator
from django.core.exceptions import ValidationError
from io import BytesIO


def enforce_rating(rating):
    if not 1 <= rating <= 5:
        raise ValidationError("You must enter a rating between 1 and 5!")


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'profile_pics/user_{0}/{1}'.format(instance.id, filename)


# Create your models here.
class Topic(models.Model):
    name = models.CharField(max_length=200)
    length = models.PositiveBigIntegerField(default=12)

    def __str__(self):
        return self.name


class Course(models.Model):
    title = models.CharField(max_length=200)
    topic = models.ForeignKey(Topic, related_name='courses', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(100),
                                                                             MaxValueValidator(200)])
    hours = models.PositiveIntegerField(default=0)
    for_everyone = models.BooleanField(default=True)
    description = models.TextField(blank=True, validators=[MaxLengthValidator(300)])
    num_reviews = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class Student(User):
    LVL_CHOICES = [
        ('HS', 'High School'),
        ('UG', 'Undergraduate'),
        ('PG', 'Postgraduate'),
        ('ND', 'No Degree'),
    ]
    level = models.CharField(choices=LVL_CHOICES, max_length=2, default='HS')
    address = models.CharField(max_length=300, blank=True)
    city = models.CharField(max_length=150, blank=True)
    province = models.CharField(max_length=2, default='ON')
    registered_courses = models.ManyToManyField(Course, blank=True)
    interested_in = models.ManyToManyField(Topic)
    picture = models.ImageField(upload_to=user_directory_path, blank=True)

    def __str__(self):
        return "{0} {1} {2}".format(self.id, self.first_name, self.last_name)

    # def save(self, *args, **kwargs):
    #     with Image.open(self.picture) as im:
    #         temp = im.resize((300, 300))
    #         output = BytesIO()
    #         temp.save(output, format='PNG', quality=85)
    #         output.seek(0)
    #         self.picture = InMemoryUploadedFile(output, 'ImageField', "%s.png" % self.picture.name.split('.')[0],
    #                                             'image/jpeg', output.getbuffer().nbytes, None)
    #     super(Student, self).save(*args, **kwargs)


class Order(models.Model):
    ORD_STATUS_CHOICES = [(0, 'Cancelled'), (1, 'Confirmed'), (2, 'On Hold')]
    courses = models.ManyToManyField(Course)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    order_status = models.IntegerField(choices=ORD_STATUS_CHOICES, default=1)
    order_date = models.DateField(default=now)

    def __str__(self):
        status = str(self.ORD_STATUS_CHOICES[self.order_status][1])
        return "{0}'s order for {1} courses at ${2} is {3}".format(self.student.first_name, len(self.courses.all()),
                                                                   self.total_cost(), status.lower())

    def total_cost(self):
        return sum(course.price if course.price else 0 for course in self.courses.all())

    def total_items(self):
        return len(self.courses.all())


class Review(models.Model):
    reviewer = models.EmailField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(validators=[enforce_rating])
    comments = models.TextField(blank=True)
    date = models.DateField(default=now)

    def __str__(self):
        return "{0} rated {1} by {2}".format(self.course, self.rating, self.reviewer)

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from myapp.models import Order, Review, Student


class SearchForm(forms.Form):
    LENGTH_CHOICES = [
        (8, '8 Weeks'),
        (10, '10 Weeks'),
        (12, '12 Weeks'),
        (14, '14 Weeks'),
    ]
    name = forms.CharField(max_length=100, label="Student Name", required=False)
    length = forms.TypedChoiceField(widget=forms.RadioSelect, label="Preferred course duration",
                                    choices=LENGTH_CHOICES, required=False, coerce=int)
    max_price = forms.IntegerField(min_value=0, label="Maximum Price")


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['courses']
        widgets = {'courses': forms.CheckboxSelectMultiple(), 'order_type': forms.RadioSelect()}


class AdminOrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['student', 'courses',  'order_status']
        widgets = {'courses': forms.CheckboxSelectMultiple(), 'order_type': forms.RadioSelect()}
        labels = {'students;': u'Student Name'}


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['reviewer', 'course', 'rating', 'comments']
        widgets = {'course': forms.RadioSelect()}
        labels = {'reviewer': 'Please enter a valid email',
                  'rating': 'Rating: An integer between 1 (worst) and 5 (best)'}


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = Student
        fields = ["username", "email", "first_name", "last_name", "city", "picture", "interested_in"]
        widgets = {"interested_in": forms.CheckboxSelectMultiple(), 'email': forms.EmailInput(),
                   'picture': forms.FileInput()}
        labels = {'picture': 'Profile Picture'}


class EditForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'city', 'picture', 'level', 'address']
        widgets = {
            'picture': forms.FileInput(),
            'level': forms.RadioSelect
        }

        def __init__(self, *args, **kwargs):
            super(EditForm, self).__init__(*args, **kwargs)
            self.fields['level'].required = False


class ForgetPasswordForm(forms.Form):
    email = forms.EmailField(max_length=100, label='Email address of the account:')

myapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.timezone import now
from .models import Topic, Course, Student, User, Order
from .forms import SearchForm, OrderForm, ReviewForm, RegisterForm, ForgetPasswordForm, EditForm, AdminOrderForm
import hashlib
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings
from datetime import datetime, timezone


def utc_to_local(utc_dt):
    return utc_dt.replace(tzinfo=timezone.utc).astimezone(tz=None)


def is_admin(user):
    """
    To check if user is admin or not
    """
    return not user.is_superuser


# Create your views here.
# def index(request):
#     top_list = Topic.objects.all().order_by('id')[:10]
#     course_list = Course.objects.all().order_by('-title')[:5]
#     response = HttpResponse()
#     heading1 = '<p>' + 'List of topics: ' + '</p>'
#     response.write(heading1)
#     for topic in top_list:
#         para = '<p>' + str(topic.id) + ': ' + str(topic) + '</p>'
#         response.write(para)
#
#     heading2 = '<p>' + 'List of Courses: ' + '</p>'
#     response.write(heading2)
#     for course in course_list:
#         para = '<p>' + str(course) + ' - ' + str(course.price) + '</p>'
#         response.write(para)
#     return response


def index(request):
    last_login = "at {}".format(utc_to_local(datetime.fromisoformat(request.session[
                                                                        'last_login'])).strftime(
        "%m/%d/%Y, %H:%M:%S")) if 'last_login' in request.session else "more than one hour ago"
    top_list = Topic.objects.all().order_by('id')[:10]
    return render(request, 'myapp/index.html', {'top_list': top_list, 'last_login': last_login})


# def about(request):
#     response = HttpResponse()
#     heading = "<h1> This is an E-learning Website! Search our Topics to find all available Courses </h1>"
#     response.write(heading)
#     return response
def about(request):
    try:
        cookie = request.COOKIES["about_visits"]
        response = render(request, "myapp/about.html", {'about_visits': int(cookie) + 1})
        response.set_cookie("about_visits", int(cookie) + 1, max_age=5 * 60)
        return response
    except KeyError:
        response = render(request, "myapp/about.html")
        response.set_cookie('about_visits', 1)
        return response


# def details(request, topic_id):
#     response = HttpResponse()
#     topic = get_object_or_404(Topic, pk=topic_id)
#     course_list = Course.objects.filter(topic__exact=topic)
#
#     heading = "<h1>" + topic.name.upper() + " - " + str(topic.length) + " weeks" + "</h1>"
#     response.write(heading)
#
#     for course in course_list:
#         para = '<p>' + str(course) + ' - ' + str(course.price) + '</p>'
#         response.write(para)
#
#     return response


def details(request, topic_id):
    topic = get_object_or_404(Topic, pk=topic_id)
    return render(request, "myapp/details.html",
                  {'topic': topic, 'course_list': topic.courses.all(), 'students': topic.student_set.all()})


def course(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    return render(request, "myapp/course.html",
                  {"course": course, "reviews": course.review_set.all(), "students": course.student_set.all()})


def findcourses(request):
    if request.method == "POST":
        unbound_form = SearchForm()
        form = SearchForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            name = data['name']
            length = data['length']
            price = data["max_price"]
            topics = Topic.objects.filter(length=length) if length != "" else Topic.objects.all()
            course_list = []
            for topic in topics:
                course_list.extend(topic.courses.filter(price__lte=price))
            return render(request, "myapp/results.html",
                          {"name": name, "course_list": course_list, "length": length,
                           "form": unbound_form, "max_price": price})
        else:
            return HttpResponse('Invalid data')
    else:
        form = SearchForm()
        return render(request, "myapp/findcourses.html", {"form": form})


@login_required(login_url='/myapp/login')
def place_order(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if request.user.is_superuser:
            form = AdminOrderForm(request.POST)

        if form.is_valid():
            courses = form.cleaned_data['courses']
            order = form.save(commit=False)

            if request.user.is_superuser:
                student = order.student
            else:
                student = Student.objects.get(id=request.user.id)
                order.student_id = request.user.id
            status = 1
            order.order_status = status
            order.save()
            form.save_m2m()
            if status == 1:
                for course in order.courses.all():
                    student.registered_courses.add(course)
            # if status == 0:
            #     for course in order.courses.all():
            #         student.registered_courses.remove(course)
            return render(request, "myapp/order_response.html",
                          {"courses": courses, "order": order})
        else:
            return render(request, "myapp/place_order.html", {"form": form})
    else:
        form = OrderForm()
        if request.user.is_superuser:
            form = AdminOrderForm()

        return render(request, "myapp/place_order.html", {"form": form})


@user_passes_test(is_admin)
def review(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review_form = form.save(commit=False)
            course = review_form.course
            review_form.save()
            course.num_reviews = course.num_reviews + 1
            course.save()
            return redirect("myapp:index")
        else:
            return render(request, "myapp/review.html", {'form': form, "errors": "Check again"})
    else:
        form = ReviewForm()
        return render(request, "myapp/review.html", {'form': form})


def user_login(request):
    if request.method == "GET":
        next_page = request.GET.get('next', '/')
        if next_page != '/':
            request.session['login_from'] = next_page
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        username = request.POST['username']
        password = request.POST["password"]
        if form.is_valid():
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    request.session['last_login'] = now().isoformat()
                    request.session.set_expiry(60 * 60)
                    # return redirect("myapp:index")
                    if 'login_from' in request.session:
                        return HttpResponseRedirect(request.session['login_from'])
                    else:
                        return redirect('myapp:index')
                else:
                    response = HttpResponse('Your account is disabled.')
        else:
            response = render(request, "myapp/login.html", {'form': form, "errors": form.errors})
    else:
        '''
        used the built in django login form.
        '''
        form = AuthenticationForm()
        response = render(request, "myapp/login.html", {'form': form})

    # if need to display forget password msg
    if "forgetPassword_msg" in request.COOKIES:
        # even deleted, it will still appear once
        response.delete_cookie("forgetPassword_msg")

    return response


@login_required(login_url='/myapp/login')
def user_logout(request):
    logout(request)
    return redirect('myapp:index')


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            form.save_m2m()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            print(user)
            if user:
                if user.is_active:
                    login(request, user)
                    return redirect('myapp:myaccount')
                else:
                    return HttpResponse('Your account is disabled.')
            else:
                return HttpResponse("Cannot login currently. Try again!")
        else:
            return render(request, "myapp/register.html", {"form": form})
    else:
        form = RegisterForm()
        return render(request, "myapp/register.html", {"form": form})


@login_required(login_url='/myapp/login')
def myaccount(request):
    courses = []
    interested_in = []
    student_id = request.user.id

    try:
        student = Student.objects.get(pk=student_id)
        # stricter if condition
        if request.user.is_authenticated and not request.user.is_staff and not request.user.is_superuser:
            # if request.user.is_authenticated:
            first_name = student.first_name
            last_name = student.last_name
            courses.extend(student.registered_courses.all())
            interested_in.extend(student.interested_in.all())
            orders = Order.objects.filter(student_id=student_id).all()
            # print(orders[0].courses.all())
            return render(request, "myapp/myaccount.html",

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" class="{% if request.COOKIES.theme == "dark" %} bg-dark-theme {% else %} bg-light-theme {% endif %}">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/main.css' %}"/>
    <title>E-Learning WebApp - {% block title %}Welcome!{% endblock %}</title>
    {% if request.COOKIES.theme == "dark" %}
        {#        <link rel="stylesheet" type="text/css"#}
        {#              href="https://cdn.jsdelivr.net/npm/bootswatch@5.1.0/dist/solar/bootstrap.min.css"/>#}
        <link rel="stylesheet" href="{% static "myapp/bootstrap.dark.min.css" %}"
        >
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/dark.css' %}"/>
    {% else %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
              crossorigin="anonymous">
    {% endif %}

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
    {% block link %} {% endblock %}
</head>
<body>
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item"><a
                        class="nav-link {% if request.resolver_match.url_name == "index" %} active {% endif %}"
                        href="{% url 'myapp:index' %}">Home</a></li>
                <li class="nav-item"><a
                        class="nav-link {% if request.resolver_match.url_name == "about" %} active {% endif %}"
                        href="{% url 'myapp:about' %}">About</a></li>


                <li class="nav-item"><a
                        class="nav-link {% if request.resolver_match.url_name == "find_courses" %} active {% endif %}"
                        href="{% url 'myapp:find_courses' %}">Find Courses</a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item"><a
                            class="nav-link {% if request.resolver_match.url_name == "place_order" %} active {% endif %}"
                            href="{% url 'myapp:place_order' %}">Place Order</a>
                    </li>
                {% endif %}

                {% if not user.is_superuser %}
                    <li class="nav-item"><a
                            class="nav-link {% if request.resolver_match.url_name == "review" %} active {% endif %}"
                            href="{% url 'myapp:review' %}">Review</a>
                    </li>
                {% endif %}

                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a
                                class="nav-link {% if request.resolver_match.url_name == "login" %} active {% endif %}"
                                href="{% url 'myapp:login' %}">Login
                        </a>
                    </li>
                {% endif %}

                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a
                                class="nav-link {% if request.resolver_match.url_name == "register" %} active {% endif %}"
                                href="{% url 'myapp:register' %}">Register Here
                        </a>
                    </li>
                {% endif %}

                {% if user.is_authenticated %}
                    <li class="nav-item"><a
                            class="nav-link {% if request.resolver_match.url_name == "myaccount" %} active {% endif %}"
                            href="{% url 'myapp:myaccount' %}">My Account</a></li>
                {% endif %}

                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'myapp:logout' %}">Logout</a></li>
                {% endif %}
            </ul>
            <div class="d-flex align-items-center">
                <label class="navbar-text mr-2 theme" for="theme-toggler">
                        Dark mode
                </label>
                <div class="form-check form-switch mx-3">
                    <input id="theme-toggler" name="theme-toggler" class="form-check-input theme" type="checkbox"
                           id="flexSwitchCheckDefault"
                            {% if request.COOKIES.theme == "dark" %} checked {% endif %}>
                </div>
            </div>

        </div>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a href="{% url "myapp:index" %}" class="navbar-brand h1">LearnO</a>

    </div>
</nav>
<div class="container-fluid container-main d-flex align-items-center justify-content-center mb-3 rounded-circle">
    <div class="col-12 d-flex flex-column justify-content-center">
        {% if not user.is_superuser %}
            <div class="card col-12 shadow-lg mb-3">
                <div class="card-body d-flex flex-column align-items-center">
                    {% if messages %}
                        {% block toasts %}
                            {% for message in messages %}
                                <div class="w-100 alert {{ message.tags }} alert-dismissible fade show" role="alert">
                                    <strong>{{ message }}</strong>
                                    <button type="button" class="btn-close" data-bs-dismiss="alert"
                                            aria-label="Close"></button>
                                </div>
                            {% endfor %}
                        {% endblock %}
                    {% endif %}
                    <div class="w-100 d-flex align-items-center justify-content-between">
                    <span class="greeting-text h1">
                    {% block myhdg %}
                        Hello
                        {{ user.get_full_name|default:"User" }}
                    {% endblock %}
                    </span>
                        {% if user.is_authenticated %}
                            <div>
                                {% if user.student.picture.url and "learn-default-profile-pic.jpg" not in user.student.picture.url %}
                                    <img class="avatar" src="{{ user.student.picture.url }}"
                                         alt="{{ user.get_full_name|default:"User" }}'s profile photo"/>
                                {% else %}
                                    <img class="avatar"
                                         src="https://robohash.org/{{ user.username|default:"User" }}?size=100x100&set=set4"
                                         alt="{{ user.get_full_name|default:"User" }}'s profile photo"/>
                                {% endif %}
                            </div>
                        {% endif %}
                    </div>
                    {% if user.is_authenticated and request.resolver_match.url_name == "myaccount" %}
                        {% block myaccount %}
                        {% endblock %}
                    {% endif %}
                </div>
            </div>
        {% endif %}
        <div class="card col-12 shadow-lg">
            <div class="card-body">
                {% block body_block %}  {% endblock %}
            </div>
        </div>
    </div>
</div>
{#<hr/>#}
{#<div>#}
{#    <ul class="footer--list">#}
{#        {% if request.resolver_match.url_name != "index" %}#}
{#            <li class="hbar1"><a href="{% url 'myapp:index' %}">Home</a><br/></li>#}
{#        {% endif %}#}
{##}
{#        {% if request.resolver_match.url_name != "about" %}#}
{#            <li class="hbar1"><a href="{% url 'myapp:about' %}">About</a></li>#}
{#        {% endif %}#}
{##}
{#        {% if request.resolver_match.url_name != "find_courses" %}#}
{#            <li class="hbar1"><a href="{% url 'myapp:find_courses' %}">Search Courses</a><br/></li>#}
{#        {% endif %}#}
{##}
{#        {% if request.resolver_match.url_name != "place_order" %}#}
{#            <li class="hbar1"><a href="{% url 'myapp:place_order' %}">Place Order</a><br/></li>#}
{#        {% endif %}#}
{##}
{#        {% if request.resolver_match.url_name != "review" %}#}
{#            <li class="hbar1"><a href="{% url 'myapp:review' %}">Review Course</a><br/></li>#}
{#        {% endif %}#}
{##}
{#        {% if not user.is_authenticated %}#}
{#            {% if request.resolver_match.url_name != "login" %}#}
{#                <li class="hbar1"><a href="{% url 'myapp:login' %}">Login</a><br/></li>#}
{#            {% endif %}#}
{#        {% endif %}#}
{##}
{#        {% if user.is_authenticated %}#}
{#            {% if request.resolver_match.url_name != "myaccount" %}#}
{#                <li class="hbar1"><a href="{% url 'myapp:myaccount' %}">Account</a><br/></li>#}
{#            {% endif %}#}
{#        {% endif %}#}
{##}
{#        {% if user.is_authenticated %}#}
{#            <li class="hbar1"><a href="{% url 'myapp:logout' %}">Logout</a><br/></li>#}
{#        {% endif %}#}
{#    </ul>#}
{#</div>#}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
<script>
    function setCookie(cName, cValue) {
        document.cookie = cName + "=" + cValue;
    }

    function getCookie(cName) {
        const name = cName + "=";
        const cDecoded = decodeURIComponent(document.cookie); //to be careful
        const cArr = cDecoded.split('; ');
        let res;
        cArr.forEach(val => {
            if (val.indexOf(name) === 0) res = val.substring(name.length);
        })
        return res;
    }

    const btn = document.getElementById("theme-toggler")

    btn.addEventListener("click", () => {
        const theme = getCookie("theme")
        console.log(theme)
        if (theme === "dark") {
            setCookie("theme", "light")
        } else {
            setCookie("theme", "dark")
        }
        window.location.reload(false);
    })
</script>
{% block scripts %}{% endblock %}
</html>

myapp/templates/myapp/change_password.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}
{% block title %} Change {{ user.username }}'s password {% endblock %}
{% block body_block %}
    <h2>Change Password</h2>
    <form action="{% url 'myapp:change_password' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-primary" name="submit" value="Update"/>
    </form>
{% endblock %}

myapp/templates/myapp/findcourses.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}
{% block title %} Find Courses {% endblock %}
{% block body_block %}
            <form class="search--form" action="{% url 'myapp:find_courses' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-primary" name="submit1" value="Find Courses"/>
            </form>
            {% block results %}  {% endblock %}
{% endblock %}

myapp/templates/myapp/forget_password.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}
{% block title %} Forget password {% endblock %}
{% block body_block %}
    {% if errors %}
        <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Error</h4>
            <strong>{{ errors }}</strong>
        </div>
    {% endif %}
    {% if helptext %}
        <h5>{{ helptext }}</h5>
    {% endif %}
    {% if local_forgetPassword_msg %}
        <div class="card">
            <div class="card-body">
                {{ local_forgetPassword_msg }}
            </div>
        </div>
    {% endif %}
    <form class="forgetpassword__form" action="{% url 'myapp:forget_password' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-primary" name="submit" value="Send new password to me"/>
    </form>

{% endblock %}

myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}
{% block title %} {{ user.username }} placed an order {% endblock %}
{% block body_block %}
    {% if courses %}
        <h2>You placed the following order</h2>
        <h3>{{ order }}</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Course</th>
                    <th>Category</th>
                    <th>Price (in $)</th>
                </tr>
            </thead>
            <tbody>
                {% for course in courses %}
                <tr>
                    <td> <a href="{% url "myapp:course" course_id=course.id %}">{{ course.title }}</a> </td>
                    <td> {{ course.topic }} </td>
                    <td> {{ course.price }} </td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td>Total</td>
                    <td></td>
                    <td> {{ order.total_cost }} </td>
                </tr>
            </tfoot>
        </table>
    {% else %}
        <div class="alert alert-warning" role="alert">
            <strong>No courses ordered!</strong>
        </div>
    {% endif %}
    <h3>
        <a href="{% url 'myapp:place_order' %}">Place a new Order</a>
    </h3>
{% endblock %}